### ISSUE TITLE
which tech use for the frontend

### ISSUE THREAD

**Issue by guivictorr** [guivictorr/tasks#5]
**Framework**
- next.js

**Styles**
- tailwind 

**Tests**
- Testing library
- jest

**data fetching**
- react-query

**Comment by isaqueveras** [comment]
I would choose to work with Tailwind CSS

**Comment by guivictorr** [comment]
> I would choose to work with tailwind css, what do you think?

i was thinking about tailwind too, i want to learn it

**Comment by isaqueveras** [comment]
> > I would choose to work with tailwind css, what do you think?
> 
> i was thinking about tailwind too, i want to learn it

I'm also studying Tailwind Css
